cmake_minimum_required(VERSION 3.31)

set(FCG_known_comps static shared)
set(FCG_comp_static NO)
set(FCG_comp_shared NO)
foreach (FCG_comp IN LISTS ${CMAKE_FIND_PACKAGE_NAME}_FIND_COMPONENTS)
    if (FCG_comp IN_LIST FCG_known_comps)
        set(FCG_comp_${FCG_comp} YES)
    else()
        set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE
                "FCG Framework does not recognize component `${FCG_comp}`.")
        set(${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
        return()
    endif()
endforeach()

if (FCG_comp_static AND FCG_comp_shared)
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE
            "FCG Framework `static` and `shared` components are mutually exclusive.")
    set(${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    return()
endif()

set(FCG_static_targets "${CMAKE_CURRENT_LIST_DIR}/FCG-static-targets.cmake")
set(FCG_shared_targets "${CMAKE_CURRENT_LIST_DIR}/FCG-shared-targets.cmake")

macro(FCG_load_targets type)
    if (NOT EXISTS "${FCG_${type}_targets}")
        set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE
                "FCG `${type}` libraries were requested but not found.")
        set(${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
        return()
    endif()
    include("${FCG_${type}_targets}")
endmacro()

if (FCG_comp_static)
    FCG_load_targets(static)
elseif (FCG_comp_shared)
    FCG_load_targets(shared)
elseif (DEFINED FCG_SHARED_LIBS AND FCG_SHARED_LIBS)
    FCG_load_targets(shared)
elseif (DEFINED FCG_SHARED_LIBS AND NOT FCG_SHARED_LIBS)
    FCG_load_targets(static)
elseif (BUILD_SHARED_LIBS)
    if (EXISTS "${FCG_shared_targets}")
        FCG_load_targets(shared)
    else()
        FCG_load_targets(static)
    endif()
else()
    if (EXISTS "${FCG_static_targets}")
        FCG_load_targets(static)
    else()
        FCG_load_targets(shared)
    endif()
endif()
