
#ifndef __FCG_HELLO_SHAPES_H__
#define __FCG_HELLO_SHAPES_H__


//////
//
// Includes
//

// C++ STL
#include <cstdint>
#include <span>

// SDL3 library
#include <SDL3/SDL.h>

// GLM library
#include <glm/glm.hpp>

// Local includes
#include <FCG/device.h>
#include <FCG/buffer.h>
#include <optional>



//////
//
// Forward declarations
//

// FCG-framework
namespace fcg {
	class Player;
}



//////
//
// Enums
//

/// The list of implemented simple shapes
enum class SimpleShapes {
	ConvexPolygon,
	PlatonicSolid,
	NUM
};

/// Shortcut alias for \ref SimpleShapes.
using SS = SimpleShapes;



//////
//
// Interfaces
//

/// Abstract interface of all simple shapes.
///
/// Shape implementations generate procedural geometry in CPU-side buffers and call \ref uploadGeometry to move the data
/// to the GPU. Concrete shapes only need to worry about the geometry; the actual SDL GPU buffer creation/upload code is
/// centralized in this base class and can be reused by all concrete shapes.
class SimpleShape
{
public:

	////
	// Types

	/// Vertex layout used by all simple shapes for now.
	struct Vertex {
		glm::vec4 position;
		glm::vec4 normal;
	};


	////
	// Construction / destruction

	/// Virtual base destructor. Releases any GPU buffers that were created via \ref uploadGeometry.
	virtual ~SimpleShape();


	////
	// Methods

	/// Human-readable name of this shape.
	[[nodiscard]] virtual auto name () const -> const char* = 0;

	/// Show the shape-specific GUI widgets in the current *Dear ImGui* window. Implementations should call
	/// \ref markDirty whenever a parameter changes.
	virtual void gui () = 0;

	/// Re-generate the geometry.
	virtual void regenerate () = 0;

	///
	inline void update (fcg::Device &device)
	{
		if (dirty())
		{
			regenerate();
			if (uploadGeometry(device, vertices(), indices()))
				clearDirty();
		}
	}


	////
	// Interface properties

	/// The primitive type that this shape's geometry is to be interpreted as.
	[[nodiscard]] virtual auto primitiveType () const -> SDL_GPUPrimitiveType = 0;

	/// The CPU-side vertex data, as generated by the last \ref regenerate call.
	[[nodiscard]] virtual auto vertices () const -> std::span<const Vertex> = 0;

	/// The CPU-side index data, as generated by the last \ref regenerate call.
	[[nodiscard]] virtual auto indices () const -> std::span<const uint32_t> = 0;


	////
	// Accessors

	/// Whether the shape's parameters have changed since the last \ref regenerate.
	[[nodiscard]] inline auto dirty () const -> bool {
		return m_dirty;
	}

	/// The GPU vertex buffer, empty if \ref regenerate has not been called successfully yet.
	[[nodiscard]] inline auto vertexBuffer () const -> const fcg::Buffer& {
		return m_vertexBuffer;
	}

	/// The GPU index buffer, empty if \ref regenerate has not been called successfully yet.
	[[nodiscard]] inline auto indexBuffer () const -> const fcg::Buffer& {
		return m_indexBuffer;
	}

	/// Number of indices currently stored in \ref indexBuffer.
	[[nodiscard]] inline auto numIndices () const -> std::size_t {
		return m_numIndices;
	}


protected:

	////
	// State management

	/// Mark the shape as needing a rebuild.
	inline void markDirty () {
		m_dirty = true;
	}

	/// Clear the dirty flag. Implementations should call this after a successful \ref regenerate.
	inline void clearDirty () {
		m_dirty = false;
	}

	/// Submit replacement geometry in one batch, committing both buffers only after successful submission.
	/// \param device Device that owns this shape's buffers; must outlive the shape.
	/// \param vertices Vertex elements copied before return. \param indices 32-bit index elements.
	/// \returns True on success (including empty geometry), false on failure with the old geometry retained.
	[[nodiscard]] auto uploadGeometry (
		fcg::Device &device, std::span<const Vertex> vertices, std::span<const std::uint32_t> indices
	) -> bool;


private:

	////
	// Fields

	/// Dirty flag: parameters changed, geometry needs to be regenerated.
	bool m_dirty = true;

	/// Reusable staging, created on the first upload and bound to that device.
	std::optional<fcg::UploadBatch> uploads;

	/// Fixed-size GPU vertex allocation, empty until a successful upload.
	fcg::Buffer m_vertexBuffer;

	/// Fixed-size GPU index allocation, empty until a successful upload.
	fcg::Buffer m_indexBuffer;

	/// Number of uploaded indices.
	std::size_t m_numIndices = 0;
};


#endif  // __FCG_HELLO_SHAPES_H__
