
#ifndef __FCG_HELLO_SHAPES_H__
#define __FCG_HELLO_SHAPES_H__


//////
//
// Includes
//

// C++ STL
#include <cstdint>
#include <span>

// SDL3 library
#include <SDL3/SDL.h>

// GLM library
#include <glm/glm.hpp>

// Local includes
#include <FCG/device.h>



//////
//
// Forward declarations
//

// FCG-framework
namespace fcg {
	class Player;
}



//////
//
// Enums
//

/// The list of implemented simple shapes
enum class SimpleShapes {
	ConvexPolygon,
	PlatonicSolid,
	NUM
};

/// Shortcut alias for \ref SimpleShapes.
using SS = SimpleShapes;



//////
//
// Interfaces
//

/// Abstract interface of all simple shapes.
///
/// Shape implementations generate procedural geometry in CPU-side buffers and call \ref uploadGeometry to move the data
/// to the GPU. Concrete shapes only need to worry about the geometry; the actual SDL GPU buffer creation/upload code is
/// centralized in this base class and can be reused by all concrete shapes.
class SimpleShape
{
public:

	////
	// Types

	/// Vertex layout used by all simple shapes for now.
	struct Vertex {
		glm::vec4 position;
		glm::vec4 normal;
	};


	////
	// Construction / destruction

	/// Virtual base destructor. Releases any GPU buffers that were created via \ref uploadGeometry.
	virtual ~SimpleShape();


	////
	// Methods

	/// Human-readable name of this shape.
	[[nodiscard]] virtual auto name () const -> const char* = 0;

	/// Show the shape-specific GUI widgets in the current *Dear ImGui* window. Implementations should call
	/// \ref markDirty whenever a parameter changes.
	virtual void gui () = 0;

	/// Re-generate the geometry.
	virtual void regenerate () = 0;

	///
	inline void update (fcg::Device &device)
	{
		if (dirty())
		{
			regenerate();
			uploadGeometry(
				device, vertices().data(), vertices().size()*sizeof(Vertex),
				indices().data(), indices().size()
			);
			clearDirty();
		}
	}


	////
	// Interface properties

	/// The primitive type that this shape's geometry is to be interpreted as.
	[[nodiscard]] virtual auto primitiveType () const -> SDL_GPUPrimitiveType = 0;

	/// The CPU-side vertex data, as generated by the last \ref rebuild call.
	[[nodiscard]] virtual auto vertices () const -> std::span<const Vertex> = 0;

	/// The CPU-side index data, as generated by the last \ref rebuild call.
	[[nodiscard]] virtual auto indices () const -> std::span<const uint32_t> = 0;


	////
	// Accessors

	/// Whether the shape's parameters have changed since the last \ref rebuild.
	[[nodiscard]] inline auto dirty () const -> bool {
		return m_dirty;
	}

	/// The GPU vertex buffer, or `nullptr` if \ref rebuild has not been called successfully yet.
	[[nodiscard]] inline auto vertexBuffer () const -> SDL_GPUBuffer* {
		return m_vertexBuffer;
	}

	/// The GPU index buffer, or `nullptr` if \ref rebuild has not been called successfully yet.
	[[nodiscard]] inline auto indexBuffer () const -> SDL_GPUBuffer* {
		return m_indexBuffer;
	}

	/// Number of indices currently stored in \ref indexBuffer.
	[[nodiscard]] inline auto numIndices () const -> std::size_t {
		return m_numIndices;
	}


protected:

	////
	// State management

	/// Mark the shape as needing a rebuild.
	inline void markDirty () {
		m_dirty = true;
	}

	/// Clear the dirty flag. Implementations should call this after a successful \ref rebuild.
	inline void clearDirty () {
		m_dirty = false;
	}

	/// Upload vertex/index data to the GPU, replacing any buffers that were previously created.
	///
	/// This helper centralizes all SDL GPU buffer management so that concrete shapes do not need
	/// to include SDL headers or deal with transfer buffers directly.
	///
	/// \param device        The active FCG device wrapper.
	/// \param vertexData    Raw pointer to the vertex data.
	/// \param vertexDataSize Size of the vertex data in bytes.
	/// \param indexData     Pointer to an array of 32-bit indices.
	/// \param numIndices    Number of indices in \p indexData.
	void uploadGeometry (
		fcg::Device &device, const void *vertexData, std::size_t vertexDataSize, const std::uint32_t *indexData,
		std::size_t numIndices
	);


private:

	////
	// Fields

	/// Dirty flag: parameters changed, geometry needs to be regenerated.
	bool m_dirty = true;

	/// Cached GPU device handle, captured on first \ref uploadGeometry so the destructor can release
	/// buffers without requiring an explicit device reference.
	fcg::Device *device = nullptr;

	/// GPU vertex buffer handle.
	SDL_GPUBuffer *m_vertexBuffer = nullptr;

	/// GPU index buffer handle.
	SDL_GPUBuffer *m_indexBuffer = nullptr;

	/// Number of uploaded indices.
	std::size_t m_numIndices = 0;
};



//////
//
// Inlined class defintions
//

// The convex polygon shape.
#include "shapes/convex_poly.h"

// The platonic solid shape.
#include "shapes/platonic_solid.h"


#endif  // __FCG_HELLO_SHAPES_H__
