
//////
//
// Includes
//

// C++ STL
#include <format>
#include <string>
#include <string_view>

// Embedded framework resources (generated by cpp-embedlib)
#include <fcg-shaders.h>

// FCG Framework
#include <FCG/res.h>



//////
//
// Module-private symbols
//

// Anonymous namespace begin
namespace {

/// The file suffix of each shader stage.
constexpr auto stageSuffix (fcg::ShaderStage stage) -> const char* {
	switch (stage) {
		case fcg::ShaderStage::VERTEX:   return "vert";
		case fcg::ShaderStage::FRAGMENT: return "frag";
		case fcg::ShaderStage::COMPUTE:  return "comp";
	}
	return "";
}

/// Find an embedded file, excluding directories and missing entries.
auto tryOpen (const cpp_embedlib::EmbeddedFS &resources, std::string_view path)
	-> std::optional<cpp_embedlib::Entry>
{
	const auto it = resources.find(path);
	if (it == resources.end() || !(*it).is_file())
		return std::nullopt;
	return *it;
}

// Anonymous namespace end
}



//////
//
// Module namespace open
//

/// Our module namespace.
namespace fcg::res {



//////
//
// Class implementations
//

////
// Shader

auto Shader::stages () const -> std::vector<ShaderStage> {
	std::vector<ShaderStage> result;
	for (std::size_t i = 0; i < stageData.size(); i ++)
		if (stageData[i])
			result.push_back(static_cast<ShaderStage>(i));
	return result;
}

auto Shader::stage (ShaderStage stage) const -> std::optional<ShaderStageData> {
	const auto &entry = stageData[static_cast<std::size_t>(stage)];
	if (!entry)
		return std::nullopt;
	return *entry;
}



//////
//
// Function implementations
//

auto shader (std::string_view name) -> std::optional<Shader> {
	return shader(fcg::res::shaders::FS, name);
}

auto shader (const cpp_embedlib::EmbeddedFS &resources, std::string_view name) -> std::optional<Shader>
{
	// Match the configure-time name contract before constructing lookup paths.
	if (name.empty() || name.find_first_not_of("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-")
		!= std::string_view::npos)
		return std::nullopt;

	Shader result;
	result.m_name = name;

	// Probe each stage's compiled blob; the raw source sits right next to it
	for (auto stage : {ShaderStage::VERTEX, ShaderStage::FRAGMENT, ShaderStage::COMPUTE})
	{
		const std::string base = std::format("{}/{}.{}", name, name, stageSuffix(stage));
		auto spirv = tryOpen(resources, base + ".spv");
		if (!spirv)
			continue;
		auto source = tryOpen(resources, base + ".glsl");
		result.stageData[static_cast<std::size_t>(stage)] = ShaderStageData {
			.stage = stage, .spirv = std::as_bytes(*spirv->bytes()),
			.source = source ? *source->text() : std::string_view(),
		};
	}

	if (result.stages().empty())
		return std::nullopt;
	return result;
}



//////
//
// Namespaces close
//

// Our module namespace
}
