/**
 * \defgroup fcg_resources Resources
 * \ingroup fcg_components
 *
 * <code>\ref fcg::res::Shader</code> represents embedded shader resources. <code>\ref fcg::res::ShaderStageData</code>
 * describes the artifacts for one shader stage.
 *
 * \par Guide incomplete
 * This guide is a stub. Consult the API declarations below for currently documented behavior.
 *
 * \section fcg_resources_workflows Common workflows
 * Guide incomplete: workflow descriptions remain to be investigated and written.
 *
 * \section fcg_resources_lifetime Ownership and lifetime
 * Guide incomplete: consult individual type and member contracts.
 *
 * \section fcg_resources_errors Errors
 * Guide incomplete: error handling remains to be investigated and written.
 *
 * \section fcg_resources_examples Examples
 * Guide incomplete: worked examples remain to be added and compiled.
 *
 * \see \ref fcg_devices
 */


#ifndef __FCG_RES_H__
#define __FCG_RES_H__


//////
//
// Includes
//

// C++ STL
#include <array>
#include <cstddef>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <vector>

// FCG Framework
#include <FCG/device.h>



//////
//
// Forward declarations
//

/// cpp-embedlib as defined by the generated resource headers
namespace cpp_embedlib {
	class EmbeddedFS;
}



//////
//
// Namespaces open
//

/// Our module namespace.
namespace fcg::res {

/** \addtogroup fcg_resources
 * @{
 */



//////
//
// Structs & enums
//

/// The embedded artifacts of one shader stage: the compiled SPIR-V blob and the raw GLSL source it was built from (the
/// latter kept for readable error messages from runtime shader translation).
struct ShaderStageData
{
	/// The stage this data set belongs to.
	ShaderStage stage;

	/// The compiled SPIR-V bytecode.
	std::span<const std::byte> spirv;

	/// The raw GLSL source code the SPIR-V was compiled from.
	std::string_view source;
};



//////
//
// Classes
//

/// A logical shader registered via the build system's \c fcg_add_shader, composed of one or more shader stages. The
/// stage data consists of borrowed views into embedded storage. The binary providing that storage must remain loaded
/// for the lifetime of the shader and any copied stage data.
class FCG_FRAMEWORK_EXPORT Shader
{
	////
	// Friend declarations

	/// Only resource lookup function, which is the only place where shaders may be constructed. The friend
	/// declaration repeats the export macro: \c dllexport is a linkage attribute, and MSVC rejects a friend
	/// declaration that disagrees with the namespace-scope declaration about it (C2375).
	friend FCG_FRAMEWORK_EXPORT auto shader (const cpp_embedlib::EmbeddedFS &resources, std::string_view name) -> std::optional<Shader>;


public:

	////
	// Accessors

	/// The shader's name, as given to \c fcg_add_shader.
	[[nodiscard]] inline auto name () const -> const std::string& {
		return m_name;
	}

	/// The stages this shader is composed of.
	[[nodiscard]] auto stages () const -> std::vector<ShaderStage>;

	/// Lookup of one stage's embedded data; \c std::nullopt if the shader has no such stage.
	[[nodiscard]] auto stage (ShaderStage stage) const -> std::optional<ShaderStageData>;


private:

	////
	// Object construction/destruction

	/// Private default constructor.
	Shader() = default;


	////
	// Fields

	/// The shader's name.
	std::string m_name;

	/// Per-stage data, indexed as the stage enum. Empty optionals indicate stages the shader does not have.
	std::array<std::optional<ShaderStageData>, 3> stageData;
};



//////
//
// Functions
//

/// Look up a logical shader in a caller-provided embedded resource filesystem.
///
/// \param resources
/// 	The filesystem generated by \c fcg_finalize_shaders. The returned shader borrows its file data; the backing
/// 	storage must outlive the shader, but the filesystem object itself need not.
/// \param name
/// 	The shader name as given to \c fcg_add_shader (ASCII letters, digits, underscores and hyphens).
///
/// \returns
/// 	The shader, or \c std::nullopt if no stages of that name are embedded. Missing source text is an empty view.
[[nodiscard]] FCG_FRAMEWORK_EXPORT auto shader (
	const cpp_embedlib::EmbeddedFS &resources, std::string_view name
) -> std::optional<Shader>;

/// Look up a built-in framework shader by name.
///
/// \param name The shader name as given to \c fcg_add_shader.
///
/// \returns The shader, or \c std::nullopt if no shader of that name is embedded.
[[nodiscard]] FCG_FRAMEWORK_EXPORT auto shader (std::string_view name) -> std::optional<Shader>;



/** @} */

//////
//
// Namespaces close
//

// Our module namespace
}


#endif // ifndef __FCG_RES_H__
