cmake_minimum_required(VERSION 3.31)

function(run)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Command failed: ${ARGV}\n${out}\n${err}")
    endif()
endfunction()
function(expect_failure pattern)
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(result EQUAL 0 OR NOT "${out}${err}" MATCHES "${pattern}")
        message(FATAL_ERROR "Expected failure matching ${pattern}: ${ARGN}\n${out}\n${err}")
    endif()
endfunction()
function(contains file text)
    file(READ "${file}" contents)
    string(FIND "${contents}" "${text}" position)
    if(position LESS 0)
        message(FATAL_ERROR "${file} does not contain ${text}")
    endif()
endfunction()
function(absent file text)
    file(READ "${file}" contents)
    string(FIND "${contents}" "${text}" position)
    if(NOT position LESS 0)
        message(FATAL_ERROR "${file} unexpectedly contains ${text}")
    endif()
endfunction()

# Isolated source and binary paths with spaces also exercise quoting. Never mutate the checked-in fixture.
file(REMOVE_RECURSE "${TEST_BINARY}")
set(source "${TEST_BINARY}/source with spaces")
file(COPY "${TEST_SOURCE}/" DESTINATION "${source}")
set(common "-DFCG_DOCUMENTATION_CMAKE=${FCG_DOCUMENTATION_CMAKE}" "-DFCG_DOXYFILE_TEMPLATE=${FCG_DOXYFILE_TEMPLATE}")
set(binary "${TEST_BINARY}/manual with spaces")
run("${CMAKE_COMMAND}" -S "${source}" -B "${binary}" ${common})
find_program(documentation_doxygen doxygen)
if(documentation_doxygen)
    run("${CMAKE_COMMAND}" --build "${binary}" --target fcg-docs)
    set(html "${binary}/docs/html")
    foreach(api FirstApi SecondApi ExtraApi MobileApi)
        contains("${html}/annotated.html" "${api}")
    endforeach()
    contains("${html}/structFirstApi.html" "undocumentedPublicMember")
    absent("${html}/structFirstApi.html" "hiddenPrivateMember")
    contains("${html}/group__fixture__first.html" "example_value")
    contains("${html}/fcg_library_First.html" "Fixture::First")
    contains("${html}/fcg_library_Second.html" "Fixture::Second")
    contains("${html}/fcg_library_First.html" "group__fixture__mobile.html")
    absent("${html}/fcg_library_Second.html" "group__fixture__mobile.html")
    contains("${html}/group__fcg__components.html" "group__fixture__mobile.html")
    file(READ "${binary}/docs/Doxyfile" config)
    string(REGEX MATCHALL "public headers/first.h" duplicates "${config}")
    list(LENGTH duplicates count)
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "Input not deduplicated: ${config}")
    endif()
    absent("${binary}/docs/Doxyfile" "ignored")
    run("${CMAKE_COMMAND}" -S "${source}" -B "${binary}" ${common} -DMOVE_COMPONENT=ON)
    run("${CMAKE_COMMAND}" --build "${binary}" --target fcg-docs)
    absent("${html}/fcg_library_First.html" "group__fixture__mobile.html")
    contains("${html}/fcg_library_Second.html" "group__fixture__mobile.html")
    contains("${html}/group__fcg__components.html" "group__fixture__mobile.html")
    contains("${html}/group__fixture__mobile.html" "MobileApi")
    run("${CMAKE_COMMAND}" -S "${source}" -B "${binary}" ${common} -DBAD_REFERENCE=ON)
    expect_failure("deliberately_unresolvable_reference" "${CMAKE_COMMAND}" --build "${binary}" --target fcg-docs)
    file(WRITE "${source}/bad.h" "/** \\ingroup fixture_first\n * \\snippet missing.cpp missing_snippet\n */\nstruct BadApi {};\n")
    expect_failure("missing.cpp" "${CMAKE_COMMAND}" --build "${binary}" --target fcg-docs)
    file(WRITE "${source}/bad.h" "/** \\ingroup fixture_first\n * \\unknown_documentation_command\n */\nstruct BadApi {};\n")
    expect_failure("unknown_documentation_command" "${CMAKE_COMMAND}" --build "${binary}" --target fcg-docs)
endif()
expect_failure("Conflicting documentation ownership" "${CMAKE_COMMAND}" -S "${source}" -B "${TEST_BINARY}/conflict" ${common} -DCONFLICT=ON)
run("${CMAKE_COMMAND}" -S "${source}" -B "${TEST_BINARY}/disabled" ${common} -DFCG_BUILD_DOCUMENTATION=OFF)
expect_failure("fcg-docs" "${CMAKE_COMMAND}" --build "${TEST_BINARY}/disabled" --target fcg-docs)
run("${CMAKE_COMMAND}" -S "${source}" -B "${TEST_BINARY}/unavailable" ${common} -DCMAKE_DISABLE_FIND_PACKAGE_Doxygen=ON)
expect_failure("fcg-docs" "${CMAKE_COMMAND}" --build "${TEST_BINARY}/unavailable" --target fcg-docs)
file(MAKE_DIRECTORY "${TEST_BINARY}/parent")
file(WRITE "${TEST_BINARY}/parent/CMakeLists.txt" "cmake_minimum_required(VERSION 3.31)\nproject(Embedded NONE)\nadd_subdirectory(\"${source}\" child)\n")
run("${CMAKE_COMMAND}" -S "${TEST_BINARY}/parent" -B "${TEST_BINARY}/embedded" ${common})
contains("${TEST_BINARY}/embedded/CMakeCache.txt" "FCG_BUILD_DOCUMENTATION:BOOL=OFF")
message(STATUS "Documentation registration and manual checks passed")
