
# Called only before configuring a source-built, non-vendored AVIF backend.
# An explicit disabled lookup or runtime library path remains SDL_image's responsibility.
if(CMAKE_DISABLE_FIND_PACKAGE_libavif OR
	(SDLIMAGE_AVIF_SHARED AND DEFINED SDLIMAGE_DYNAMIC_AVIF AND EXISTS "${SDLIMAGE_DYNAMIC_AVIF}"))
	return()
endif()

block(SCOPE_FOR VARIABLES PROPAGATE FCG_LIBAVIF_BUILT_HERE libavif_SOURCE_DIR libavif_BINARY_DIR)
	set(avif_provided_target OFF)
	if(TARGET avif)
		set(avif_provided_target ON)
	else()
		# VERSION is the minimum accepted system version; GIT_TAG independently pins the source fallback.
		CPMFindPackage(
			NAME libavif
			GITHUB_REPOSITORY AOMediaCodec/libavif
			GIT_TAG v1.4.2
			VERSION 1.0
			DOWNLOAD_ONLY YES
		)
	endif()
	if(NOT TARGET avif AND libavif_SOURCE_DIR)
		# Upstream force-caches codec choices. Keep framework defaults scoped so reconfiguration can
		# discover newly installed decoders or enable saving, while retaining every caller-supplied value.
		set(avif_default_variables)
		foreach(feature CODEC_AOM CODEC_DAV1D CODEC_LIBGAV1 CODEC_AVM CODEC_AOM_ENCODE CODEC_AOM_DECODE
			BUILD_APPS BUILD_TESTS BUILD_EXAMPLES BUILD_MAN_PAGES LIBYUV)
			if(NOT DEFINED AVIF_${feature})
				list(APPEND avif_default_variables AVIF_${feature})
			endif()
		endforeach()
		# Use the checkout's own discovery modules, including their pkg-config/transitive link support.
		list(APPEND CMAKE_MODULE_PATH "${libavif_SOURCE_DIR}/cmake/Modules")
		set(avif_decoder_selected OFF)
		foreach(codec AOM DAV1D LIBGAV1 AVM)
			if(DEFINED AVIF_CODEC_${codec} AND NOT AVIF_CODEC_${codec} STREQUAL "OFF")
				set(avif_decoder_selected ON)
			endif()
		endforeach()
		if(NOT avif_decoder_selected AND NOT DEFINED AVIF_CODEC_AOM)
			foreach(lookup provided installed)
				foreach(pair "AOM;aom;aom" "DAV1D;dav1d;dav1d::dav1d" "LIBGAV1;libgav1;libgav1::libgav1")
					list(GET pair 0 codec)
					list(GET pair 1 package)
					list(GET pair 2 codec_target)
					if(DEFINED AVIF_CODEC_${codec} AND AVIF_CODEC_${codec} STREQUAL "OFF")
						continue()
					endif()
					if(lookup STREQUAL "installed" AND NOT TARGET ${codec_target})
						find_package(${package} QUIET)
					endif()
					if(TARGET ${codec_target})
						set(AVIF_CODEC_${codec} SYSTEM)
						set(avif_decoder_selected ON)
						break()
					endif()
				endforeach()
				if(avif_decoder_selected)
					break()
				endif()
			endforeach()
			if(NOT avif_decoder_selected)
				set(AVIF_CODEC_AOM LOCAL)
			endif()
		endif()
		# Saving needs an encoder too, even if automatic decoder selection chose dav1d/libgav1.
		set(avif_other_encoder_selected OFF)
		foreach(codec RAV1E SVT AVM)
			if(DEFINED AVIF_CODEC_${codec} AND NOT AVIF_CODEC_${codec} STREQUAL "OFF")
				set(avif_other_encoder_selected ON)
			endif()
		endforeach()
		if(SDLIMAGE_AVIF_SAVE AND NOT avif_other_encoder_selected AND NOT DEFINED AVIF_CODEC_AOM)
			if(NOT TARGET aom)
				find_package(aom QUIET)
			endif()
			if(TARGET aom)
				set(AVIF_CODEC_AOM SYSTEM)
			else()
				set(AVIF_CODEC_AOM LOCAL)
			endif()
		endif()
		foreach(feature BUILD_APPS BUILD_TESTS BUILD_EXAMPLES BUILD_MAN_PAGES LIBYUV)
			if(NOT DEFINED AVIF_${feature})
				set(AVIF_${feature} OFF)
			endif()
		endforeach()
		if(NOT DEFINED AVIF_CODEC_AOM_ENCODE)
			set(AVIF_CODEC_AOM_ENCODE "${SDLIMAGE_AVIF_SAVE}")
		endif()
		if(AVIF_CODEC_AOM STREQUAL "LOCAL" AND WIN32 AND NOT PERL_EXECUTABLE)
			# Git for Windows bundles Perl outside PATH; libaom needs it even for its portable decoder.
			find_package(Git QUIET)
			if(GIT_EXECUTABLE)
				get_filename_component(avif_git_bin "${GIT_EXECUTABLE}" DIRECTORY)
				find_program(PERL_EXECUTABLE NAMES perl HINTS "${avif_git_bin}"
					"${avif_git_bin}/../usr/bin" "${avif_git_bin}/../../usr/bin")
			endif()
		endif()
		if(AVIF_CODEC_AOM STREQUAL "LOCAL" AND NOT DEFINED AOM_TARGET_CPU AND
			CMAKE_SYSTEM_PROCESSOR MATCHES "^(AMD64|amd64|x86_64|i[3-6]86|x86)$")
			find_program(avif_assembler NAMES yasm nasm NO_CACHE)
			if(NOT avif_assembler)
				set(AOM_TARGET_CPU generic)
				message(STATUS "libavif: no x86 assembler found; building portable libaom")
			endif()
		endif()
		if(DEFINED SDLIMAGE_AVIF_SHARED)
			set(BUILD_SHARED_LIBS "${SDLIMAGE_AVIF_SHARED}")
		else()
			set(BUILD_SHARED_LIBS "${SDLIMAGE_DEPS_SHARED}")
		endif()
		set(CMAKE_POSITION_INDEPENDENT_CODE ON)
		if(AVIF_CODEC_AOM STREQUAL "LOCAL" AND AVIF_CODEC_AOM_ENCODE)
			# libavif's decoder-only build caches this flag as INTERNAL=0. Restore libaom's default
			# when enabling encoding later; explicit command-line/configuration choices retain precedence.
			get_property(avif_encoder_flag_type CACHE CONFIG_AV1_ENCODER PROPERTY TYPE)
			get_property(avif_encoder_flag_help CACHE CONFIG_AV1_ENCODER PROPERTY HELPSTRING)
			if(avif_encoder_flag_type STREQUAL "INTERNAL" AND avif_encoder_flag_help STREQUAL "")
				unset(CONFIG_AV1_ENCODER CACHE)
			endif()
		endif()
		add_subdirectory("${libavif_SOURCE_DIR}" "${libavif_BINARY_DIR}" EXCLUDE_FROM_ALL)
		get_directory_property(avif_aom_decoder DIRECTORY "${libavif_SOURCE_DIR}" DEFINITION AVIF_CODEC_AOM_DECODE)
		set(avif_decoder_available OFF)
		foreach(codec AOM DAV1D LIBGAV1 AVM)
			get_directory_property(enabled DIRECTORY "${libavif_SOURCE_DIR}" DEFINITION AVIF_CODEC_${codec}_ENABLED)
			if(enabled AND (NOT codec STREQUAL "AOM" OR avif_aom_decoder))
				set(avif_decoder_available ON)
			endif()
		endforeach()
		if(NOT avif_decoder_available)
			message(FATAL_ERROR "Source-built libavif requires an enabled AV1 decoder for SDL_image")
		endif()
		foreach(variable IN LISTS avif_default_variables)
			unset(${variable} CACHE)
		endforeach()
		set(FCG_LIBAVIF_BUILT_HERE ON)
	endif()
	if(NOT TARGET avif)
		message(FATAL_ERROR "libavif dependency resolution did not provide required target avif")
	endif()
	# DOWNLOAD_ONLY does not create CPM's usual package redirect. Publish the already-resolved target
	# for SDL_image's unconditional find_package(libavif), without exporting or installing a new package.
	if(FCG_LIBAVIF_BUILT_HERE OR avif_provided_target)
		include(CMakePackageConfigHelpers)
		if(FCG_LIBAVIF_BUILT_HERE)
			get_directory_property(avif_package_version DIRECTORY "${libavif_SOURCE_DIR}" DEFINITION PROJECT_VERSION)
		elseif(DEFINED libavif_VERSION)
			set(avif_package_version "${libavif_VERSION}")
		else()
			set(avif_package_version 1.0)
		endif()
		file(WRITE "${CMAKE_FIND_PACKAGE_REDIRECTS_DIR}/libavif-config.cmake"
			"if(NOT TARGET avif)\n  set(libavif_FOUND FALSE)\nendif()\n")
		write_basic_package_version_file("${CMAKE_FIND_PACKAGE_REDIRECTS_DIR}/libavif-config-version.cmake"
			VERSION "${avif_package_version}" COMPATIBILITY SameMajorVersion)
	endif()
endblock()
