# AVIF resolution fixtures supply all sources/packages explicitly and never download at test time.
set(SDLIMAGE_AVIF ON)
set(SDLIMAGE_STRICT ON)
set(avif_fixture_headers "${IMAGE_DEPENDENCY_SOURCE}/VisualC/external/include")
set(CPM_libavif_SOURCE "${CMAKE_CURRENT_LIST_DIR}/avif-source")
if(MODE MATCHES "^avif-real")
    set(CPM_libavif_SOURCE "${TEST_LIBAVIF_SOURCE}")
    set(FETCHCONTENT_SOURCE_DIR_LIBAOM "${TEST_LIBAOM_SOURCE}")
    set(CPM_DOWNLOAD_libavif ON)
    set(CMAKE_DISABLE_FIND_PACKAGE_aom TRUE)
    set(CMAKE_DISABLE_FIND_PACKAGE_dav1d TRUE)
    set(CMAKE_DISABLE_FIND_PACKAGE_libgav1 TRUE)
elseif(MODE STREQUAL "avif-provided")
    add_library(avif INTERFACE)
    target_include_directories(avif INTERFACE "${avif_fixture_headers}")
elseif(MODE MATCHES "^avif-package")
    set(avif_package_dir "${CMAKE_CURRENT_BINARY_DIR}/libavif-package")
    file(MAKE_DIRECTORY "${avif_package_dir}")
    file(WRITE "${avif_package_dir}/libavif-config.cmake"
        "if(NOT TARGET avif)\nadd_library(avif INTERFACE IMPORTED)\n"
        "set_target_properties(avif PROPERTIES INTERFACE_INCLUDE_DIRECTORIES \"${avif_fixture_headers}\")\nendif()\n")
    include(CMakePackageConfigHelpers)
    write_basic_package_version_file("${avif_package_dir}/libavif-config-version.cmake"
        VERSION 1.1.0 COMPATIBILITY SameMajorVersion)
    set(libavif_DIR "${avif_package_dir}" CACHE PATH "Older compatible installed package" FORCE)
elseif(MODE STREQUAL "avif-vendored")
    # Vendoring belongs to SDL_image. A stand-in backend makes this selection test platform independent.
    set(SDLIMAGE_VENDORED ON)
    set(image_fixture_dir "${CMAKE_CURRENT_BINARY_DIR}/vendored-image")
    file(MAKE_DIRECTORY "${image_fixture_dir}")
    set(image_fixture "cmake_minimum_required(VERSION 3.31)\nproject(SDL3_image VERSION 3.4.4)\n"
        "add_library(image INTERFACE)\nadd_library(SDL3_image::SDL3_image ALIAS image)\n")
    string(JOIN "" image_fixture ${image_fixture})
    foreach(codec AVIF BMP GIF JPG JXL LBM PCX PNG PNM QOI SVG TGA TIF WEBP XCF XPM XV)
        string(APPEND image_fixture "set(SDLIMAGE_${codec}_ENABLED OFF)\n")
    endforeach()
    string(APPEND image_fixture "set(SDLIMAGE_AVIF_ENABLED ON)\n")
    file(WRITE "${image_fixture_dir}/CMakeLists.txt" "${image_fixture}")
    set(CPM_SDL3_image_SOURCE "${image_fixture_dir}")
else()
    set(CPM_DOWNLOAD_libavif ON)
    # Fake discovery modules isolate selection from whatever codecs happen to be installed on the host.
    set(avif_modules "${CMAKE_CURRENT_BINARY_DIR}/avif-modules")
    file(MAKE_DIRECTORY "${avif_modules}")
    foreach(package aom dav1d libgav1)
        file(WRITE "${avif_modules}/Find${package}.cmake" "set(${package}_FOUND FALSE)\n")
    endforeach()
    list(PREPEND CMAKE_MODULE_PATH "${avif_modules}")
    if(MODE STREQUAL "avif-system")
        file(WRITE "${avif_modules}/Findaom.cmake" "add_library(aom INTERFACE IMPORTED)\nset(aom_FOUND TRUE)\n")
    elseif(MODE STREQUAL "avif-dav1d")
        file(WRITE "${avif_modules}/Finddav1d.cmake"
            "add_library(dav1d::dav1d INTERFACE IMPORTED)\nset(dav1d_FOUND TRUE)\n")
    elseif(MODE STREQUAL "avif-gav1")
        file(WRITE "${avif_modules}/Findlibgav1.cmake"
            "add_library(libgav1::libgav1 INTERFACE IMPORTED)\nset(libgav1_FOUND TRUE)\n")
    elseif(MODE STREQUAL "avif-provided-dav1d")
        add_library(dav1d::dav1d INTERFACE IMPORTED)
        file(WRITE "${avif_modules}/Findaom.cmake"
            "message(FATAL_ERROR \"Looked up AOM despite a provided decoder\")\n")
    elseif(MODE STREQUAL "avif-codec-provided")
        add_library(aom INTERFACE IMPORTED)
    elseif(MODE STREQUAL "avif-overrides")
        set(AVIF_CODEC_DAV1D SYSTEM CACHE STRING "Explicit decoder")
        set(AVIF_CODEC_AOM OFF CACHE STRING "Explicitly disabled AOM")
        set(AOM_TARGET_CPU fixture-cpu CACHE STRING "Caller CPU choice")
        set(AVIF_CODEC_AOM_ENCODE OFF CACHE BOOL "Caller encoder choice")
    elseif(MODE STREQUAL "avif-save")
        set(SDLIMAGE_AVIF_SAVE ON CACHE BOOL "Explicit saving")
    elseif(MODE STREQUAL "avif-alternate-encoder")
        set(SDLIMAGE_AVIF_SAVE ON)
        set(AVIF_CODEC_DAV1D SYSTEM)
        set(AVIF_CODEC_RAV1E SYSTEM)
    elseif(MODE STREQUAL "avif-shared")
        set(SDLIMAGE_AVIF_SHARED ON)
    elseif(MODE STREQUAL "avif-no-decoder")
        set(AVIF_CODEC_AOM OFF)
    elseif(NOT MODE STREQUAL "avif-local")
        message(FATAL_ERROR "Unknown AVIF fixture mode: ${MODE}")
    endif()
endif()
if(MODE MATCHES "cache$")
    unset(SDLIMAGE_AVIF)
    set(SDLIMAGE_AVIF ON CACHE BOOL "Cache AVIF opt-in")
endif()
