include_guard(GLOBAL)

# Register source-tree documentation even when a library's binary is disabled.
# Relative paths are resolved at the call site, including calls in subdirectories.
function(fcg_register_documentation)
	cmake_parse_arguments(PARSE_ARGV 0 DOC "" "LIBRARY;LINK_TARGET;GUIDE" "COMPONENTS;INPUTS;EXAMPLE_DIRS;PREDEFINED")
	if(DOC_UNPARSED_ARGUMENTS OR DOC_KEYWORDS_MISSING_VALUES OR NOT DOC_LIBRARY OR NOT DOC_LINK_TARGET)
		message(FATAL_ERROR "fcg_register_documentation requires LIBRARY and LINK_TARGET and valid nonempty arguments")
	endif()
	if(NOT DOC_LIBRARY MATCHES "^[A-Za-z][A-Za-z0-9_]*$")
		message(FATAL_ERROR "Documentation LIBRARY must be an identifier: ${DOC_LIBRARY}")
	endif()
	get_property(previous GLOBAL PROPERTY "FCG_DOC_${DOC_LIBRARY}_LINK_TARGET")
	if(previous AND NOT previous STREQUAL DOC_LINK_TARGET)
		message(FATAL_ERROR "Conflicting LINK_TARGET for documentation library ${DOC_LIBRARY}")
	endif()
	set_property(GLOBAL PROPERTY "FCG_DOC_${DOC_LIBRARY}_LINK_TARGET" "${DOC_LINK_TARGET}")
	set_property(GLOBAL APPEND PROPERTY FCG_DOC_LIBRARIES "${DOC_LIBRARY}")
	if(DOC_GUIDE)
		if(NOT DOC_GUIDE MATCHES "^[A-Za-z][A-Za-z0-9_]*$")
			message(FATAL_ERROR "Documentation GUIDE must be a page identifier: ${DOC_GUIDE}")
		endif()
		get_property(previous GLOBAL PROPERTY "FCG_DOC_${DOC_LIBRARY}_GUIDE")
		if(previous AND NOT previous STREQUAL DOC_GUIDE)
			message(FATAL_ERROR "Conflicting GUIDE for documentation library ${DOC_LIBRARY}")
		endif()
		set_property(GLOBAL PROPERTY "FCG_DOC_${DOC_LIBRARY}_GUIDE" "${DOC_GUIDE}")
	endif()
	foreach(component IN LISTS DOC_COMPONENTS)
		if(NOT component MATCHES "^[A-Za-z][A-Za-z0-9_]*$")
			message(FATAL_ERROR "Documentation component must be a stable group identifier: ${component}")
		endif()
		get_property(owner GLOBAL PROPERTY "FCG_DOC_OWNER_${component}")
		if(owner AND NOT owner STREQUAL DOC_LIBRARY)
			message(FATAL_ERROR "Conflicting documentation ownership for ${component}: ${owner} and ${DOC_LIBRARY}")
		endif()
		set_property(GLOBAL PROPERTY "FCG_DOC_OWNER_${component}" "${DOC_LIBRARY}")
	endforeach()
	foreach(kind INPUTS EXAMPLE_DIRS)
		foreach(path IN LISTS DOC_${kind})
			get_filename_component(path "${path}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
			if(NOT EXISTS "${path}")
				message(FATAL_ERROR "Documentation ${kind} does not exist: ${path}")
			endif()
			set_property(GLOBAL APPEND PROPERTY "FCG_DOC_${DOC_LIBRARY}_${kind}" "${path}")
		endforeach()
	endforeach()
	foreach(kind COMPONENTS PREDEFINED)
		set_property(GLOBAL APPEND PROPERTY "FCG_DOC_${DOC_LIBRARY}_${kind}" "${DOC_${kind}}")
	endforeach()
endfunction()

# Doxygen lists use quoted, escaped strings, not CMake's semicolon notation.
function(_fcg_doc_quote output)
	set(result "")
	foreach(value IN LISTS ARGN)
		string(REPLACE "\\" "\\\\" value "${value}")
		string(REPLACE "\"" "\\\"" value "${value}")
		string(APPEND result " \"${value}\"")
	endforeach()
	set(${output} "${result}" PARENT_SCOPE)
endfunction()

# Call once after dependency setup and all registrations. The target has no binary dependencies.
function(fcg_add_documentation)
	cmake_parse_arguments(PARSE_ARGV 0 DOC "" "TEMPLATE;MAIN_PAGE" "")
	if(NOT FCG_BUILD_DOCUMENTATION)
		return()
	endif()
	if(NOT DOXYGEN_FOUND)
		message(STATUS "Doxygen not found; fcg-docs is unavailable")
		return()
	endif()
	if(DOC_UNPARSED_ARGUMENTS OR DOC_KEYWORDS_MISSING_VALUES OR NOT DOC_TEMPLATE OR NOT DOC_MAIN_PAGE)
		message(FATAL_ERROR "fcg_add_documentation requires TEMPLATE and MAIN_PAGE")
	endif()
	foreach(kind TEMPLATE MAIN_PAGE)
		get_filename_component(DOC_${kind} "${DOC_${kind}}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
	endforeach()
	set(output_dir "${PROJECT_BINARY_DIR}/docs")
	file(MAKE_DIRECTORY "${output_dir}")
	get_property(libraries GLOBAL PROPERTY FCG_DOC_LIBRARIES)
	list(REMOVE_DUPLICATES libraries)
	set(index "/**\n\\page fcg_libraries Library index\n\nLibraries and their CMake link targets. Components retain their group identities independently of library ownership.\n\n")
	set(pages "")
	set(inputs "${DOC_MAIN_PAGE}" "${output_dir}/libraries.dox")
	set(examples "")
	set(definitions "")
	foreach(library IN LISTS libraries)
		get_property(link_target GLOBAL PROPERTY "FCG_DOC_${library}_LINK_TARGET")
		get_property(components GLOBAL PROPERTY "FCG_DOC_${library}_COMPONENTS")
		list(REMOVE_DUPLICATES components)
		string(APPEND index "- \\subpage fcg_library_${library}\n")
		string(APPEND pages "/**\n\\page fcg_library_${library} ${library}\n\nCMake link target:\n\\verbatim\n${link_target}\n\\endverbatim\n\nComponents:\n")
		foreach(component IN LISTS components)
			string(APPEND pages "- \\ref ${component}\n")
		endforeach()
		get_property(guide GLOBAL PROPERTY "FCG_DOC_${library}_GUIDE")
		if(guide)
			string(APPEND pages "\nLibrary guide: \\ref ${guide}\n")
		endif()
		string(APPEND pages "*/\n\n")
		get_property(registered GLOBAL PROPERTY "FCG_DOC_${library}_INPUTS")
		foreach(path IN LISTS registered)
			if(IS_DIRECTORY "${path}")
				file(GLOB_RECURSE headers CONFIGURE_DEPENDS LIST_DIRECTORIES false
					"${path}/*.h" "${path}/*.hh" "${path}/*.hpp" "${path}/*.hxx")
			else()
				set(headers "${path}")
			endif()
			foreach(header IN LISTS headers)
				if(IS_DIRECTORY "${path}")
					file(RELATIVE_PATH relative "${path}" "${header}")
				else()
					get_filename_component(relative "${header}" NAME)
				endif()
				cmake_path(IS_PREFIX PROJECT_BINARY_DIR "${header}" NORMALIZE in_build_tree)
				# Only public headers; never extract implementation, vendor or build trees.
				if(header MATCHES "\\.(h|hh|hpp|hxx)$" AND
				   NOT in_build_tree AND
				   NOT "/${relative}" MATCHES "/(src|app|apps|applications|test|tests|dependencies|third_party|vendor|_deps|build[^/]*|cmake-build[^/]*|CMakeFiles)/")
					list(APPEND inputs "${header}")
				endif()
			endforeach()
		endforeach()
		get_property(dirs GLOBAL PROPERTY "FCG_DOC_${library}_EXAMPLE_DIRS")
		list(APPEND examples ${dirs})
		get_property(defs GLOBAL PROPERTY "FCG_DOC_${library}_PREDEFINED")
		list(APPEND definitions ${defs})
	endforeach()
	string(APPEND index "*/\n\n${pages}")
	file(WRITE "${output_dir}/libraries.dox" "${index}")
	foreach(kind inputs examples definitions)
		list(REMOVE_DUPLICATES ${kind})
	endforeach()
	_fcg_doc_quote(FCG_DOC_INPUTS ${inputs})
	_fcg_doc_quote(FCG_DOC_EXAMPLES ${examples})
	_fcg_doc_quote(FCG_DOC_PREDEFINED ${definitions})
	_fcg_doc_quote(FCG_DOC_OUTPUT "${output_dir}")
	configure_file("${DOC_TEMPLATE}" "${output_dir}/Doxyfile" @ONLY)
	add_custom_target(fcg-docs
		COMMAND "${DOXYGEN_EXECUTABLE}" "${output_dir}/Doxyfile"
		WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
		COMMENT "Generating and validating the framework manual"
		VERBATIM
	)
endfunction()
